#pragma once

#include "Ink/Document/Document.h"

namespace Ink {

// ─────────────────────────────────────────────────────────────────────────────
//  Scene — the compiled runtime scene (docs/Ink/ARCHITECTURE.md §2): the only
//  consumer of the Document and the only producer of render items. A compile
//  walks pages → layer trees in painter order and emits one Drawable per
//  enabled style piece (fills bottom-up, then strokes) of every visible path
//  node, with the world transform resolved in double.
//
//  Compositing (docs/Ink/DOCUMENT_MODEL.md §2, RENDER_GRAPH.md §4): a group is
//  a LAYER. A group that carries opacity<1, a non-Normal blend, isolate, or a
//  clip opens a COMPOSITE SCOPE — its subtree renders into its own isolation
//  target, then composites onto the parent as a unit. The compile records the
//  scope tree and tags every drawable with the scope it belongs to; the
//  Renderer plays scopes deepest-first and composites back up.
//
//  Lot 2/4 granularity: the walk is O(nodes) and runs only when the ChangeLog
//  is non-empty; finer per-change diffing layers on in the perf lots.
// ─────────────────────────────────────────────────────────────────────────────

// index into Scene::Scopes(); 0 = the page root (no isolation).
using ScopeId = std::uint32_t;
inline constexpr ScopeId kRootScope = 0;

struct CompositeScope {
    NodeId    node   = kNullNode;
    ScopeId   parent = kRootScope;
    float     opacity = 1.0f;
    BlendMode blend   = BlendMode::Normal;
    bool      isolate = false;
    // Clip: the scope's contents are masked by the clip source geometry (the
    // group's first path child, Lot 4). kNullNode = no clip.
    NodeId    clipNode = kNullNode;
    // Filled by the Renderer while playing the scope tree (transient).
    int       depth = 0;
};

struct Drawable {
    NodeId          node = kNullNode;
    DMat23          world;              // node-local → document (double)
    std::uint64_t   pathHash = 0;
    const PathData* path = nullptr;     // borrowed; valid until the next compile
    bool            isStroke = false;
    std::uint8_t    pieceIndex = 0;     // index into style.fills / style.strokes
    FillRule        rule = FillRule::NonZero;   // fill pieces
    Stroke          stroke;                     // stroke pieces (geometry params)
    Color           color;              // linear straight (premultiplied later)
    ScopeId         scope = kRootScope; // the composite scope this belongs to
    bool            isClipSource = false;  // draws to the clip stencil, not color
};

class Scene {
public:
    // Recompile if the document changed since the last compile (or `force`).
    // Drains the document's ChangeLog. Returns true when the drawable list
    // was rebuilt (GPU tables must resync).
    bool Compile(Document& doc, bool force = false);

    const std::vector<Drawable>&      Drawables() const { return drawables_; }
    const std::vector<CompositeScope>& Scopes()   const { return scopes_; }
    // Deepest composite-scope nesting in the scene (drives the isolation
    // target reservation — RENDER_GRAPH.md §2).
    int MaxScopeDepth() const { return maxDepth_; }
    // Document version this scene reflects (mixed into view signatures).
    std::uint64_t Version() const { return version_; }
    // Document-space bounds (pages ∪ node anchor boxes) — drives fit-view.
    Rect Bounds() const { return bounds_; }

private:
    // Emit `n` (and its subtree) once per instancing transform generated by
    // its modifier stack, composed onto `parentWorld`. `instDepth` guards
    // InstanceNode recursion (cycle/blow-up clamp).
    void EmitNode(const Document& doc, const Node& n, const DMat23& parentWorld,
                  ScopeId scope, int instDepth);
    // Emit the node's OWN content (a path's style pieces, a group's children,
    // an instance's target) at exactly `world` — the leaf of the modifier
    // expansion.
    void EmitContent(const Document& doc, const Node& n, const DMat23& world,
                     ScopeId scope, int instDepth);
    // Emit the style pieces (fills incl. pattern expansion, then strokes) of a
    // path node at `world`.
    void EmitPath(const Document& doc, const Node& n, const DMat23& world,
                  ScopeId scope);
    // Expand a pattern fill: motif instances on a lattice over the fill bbox.
    void EmitPattern(const Document& doc, const Fill& fill, const Node& host,
                     const DMat23& world, ScopeId scope);
    // A group that composites as a unit opens a scope; returns its id (or the
    // parent scope when the group is a plain pass-through layer).
    ScopeId OpenScopeIfNeeded(const Document& doc, const Node& group,
                              ScopeId parent, int depth);
    void GrowBounds(DVec2 p);

    std::vector<Drawable>       drawables_;
    std::vector<CompositeScope> scopes_;
    std::vector<PathData>       pageRects_;   // stable storage for page substrates
    int           maxDepth_ = 0;
    std::uint64_t version_  = 0;
    bool          compiled_ = false;
    Rect          bounds_{};
    bool          boundsValid_ = false;
};

} // namespace Ink
