#pragma once

#include "Ink/Document/Document.h"

#include <deque>
#include <unordered_map>

namespace Ink {

// ─────────────────────────────────────────────────────────────────────────────
//  Scene — the compiled runtime scene (docs/Ink/ARCHITECTURE.md §2): the only
//  consumer of the Document and the only producer of render items. A compile
//  walks pages → layer trees in painter order and emits one Drawable per
//  enabled style piece (fills bottom-up, then strokes) of every visible path
//  node, with the world transform resolved in double.
//
//  Compositing (docs/Ink/DOCUMENT_MODEL.md §2, RENDER_GRAPH.md §4): a group is
//  a LAYER. A group that carries opacity<1, a non-Normal blend, isolate, or a
//  clip opens a COMPOSITE SCOPE — its subtree renders into its own isolation
//  target, then composites onto the parent as a unit. The compile records the
//  scope tree and tags every drawable with the scope it belongs to; the
//  Renderer plays scopes deepest-first and composites back up.
//
//  Lot 2/4 granularity: the walk is O(nodes) and runs only when the ChangeLog
//  is non-empty; finer per-change diffing layers on in the perf lots.
// ─────────────────────────────────────────────────────────────────────────────

// index into Scene::Scopes(); 0 = the page root (no isolation).
using ScopeId = std::uint32_t;
inline constexpr ScopeId kRootScope = 0;

struct CompositeScope {
    NodeId    node   = kNullNode;
    ScopeId   parent = kRootScope;
    float     opacity = 1.0f;
    BlendMode blend   = BlendMode::Normal;
    bool      isolate = false;
    // Clip: the scope's contents are masked by the clip source geometry (the
    // group's first path child, Lot 4). kNullNode = no clip.
    NodeId    clipNode = kNullNode;
    // Filled by the Renderer while playing the scope tree (transient).
    int       depth = 0;
};

// How a drawable interacts with the pass's stencil CLIP mask (docs/Ink/
// RENDER_GRAPH.md §ClipPass). The mask value is always 1: MaskWrite rasterises
// the mask (no colour), MaskClear erases it back to 0 (so sequential clipped
// regions in one pass never leak into each other), Clipped draws colour only
// where the mask is set. Clipping is resolved at VIEW tolerance by the normal
// mesh pipeline — vector-exact at any zoom.
enum class ClipRole : std::uint8_t { None = 0, MaskWrite, MaskClear, Clipped };

struct Drawable {
    NodeId          node = kNullNode;
    // The node SELECTION maps to (picking, outlines): an instance's subtree
    // picks the instance, a pattern motif copy picks its host. Equals `node`
    // for plain content.
    NodeId          owner = kNullNode;
    DMat23          world;              // node-local → document (double)
    std::uint64_t   pathHash = 0;
    const PathData* path = nullptr;     // borrowed; valid until the next compile
    bool            isStroke = false;
    std::uint8_t    pieceIndex = 0;     // index into style.fills / style.strokes
    FillRule        rule = FillRule::NonZero;   // fill pieces
    Stroke          stroke;                     // stroke pieces (geometry params)
    Color           color;              // linear straight (premultiplied later)
    ScopeId         scope = kRootScope; // the composite scope this belongs to
    ClipRole        clip = ClipRole::None;  // stencil interaction (see above)
    bool            isClipSource = false;   // mask geometry — never picked/painted
};

class Scene {
public:
    // Recompile if the document changed since the last compile (or `force`).
    // Drains the document's ChangeLog. Returns true when the drawable list
    // was rebuilt (GPU tables must resync).
    bool Compile(Document& doc, bool force = false);

    const std::vector<Drawable>&      Drawables() const { return drawables_; }
    const std::vector<CompositeScope>& Scopes()   const { return scopes_; }
    // Deepest composite-scope nesting in the scene (drives the isolation
    // target reservation — RENDER_GRAPH.md §2).
    int MaxScopeDepth() const { return maxDepth_; }
    // Document version this scene reflects (mixed into view signatures).
    std::uint64_t Version() const { return version_; }
    // Document-space bounds (pages ∪ node anchor boxes) — drives fit-view.
    Rect Bounds() const { return bounds_; }
    // Document-space bounds of one node's rendered content (all its drawables
    // incl. modifier copies; an instance's id covers its rendered subtree).
    // Conservative: Bézier control-point hull + outward stroke extent.
    // Returns false when the node produced nothing this compile.
    bool NodeBounds(NodeId owner, DRect& out) const {
        auto it = nodeBounds_.find(owner);
        if (it == nodeBounds_.end() || !it->second.valid) return false;
        out = it->second;
        return true;
    }

private:
    // Emit `n` (and its subtree) once per instancing transform generated by
    // its modifier stack, composed onto `parentWorld`. `instDepth` guards
    // InstanceNode recursion (cycle/blow-up clamp). `owner` = the selection
    // owner to stamp on drawables (kNullNode → the node itself).
    // `forceVisible` bypasses the node's own visible flag (instance targets —
    // a linked duplicate stays visible when the original is hidden).
    void EmitNode(const Document& doc, const Node& n, const DMat23& parentWorld,
                  ScopeId scope, int instDepth, NodeId owner = kNullNode,
                  bool forceVisible = false);
    // Emit the node's OWN content (a path's style pieces, a group's children,
    // an instance's target) at exactly `world` — the leaf of the modifier
    // expansion.
    void EmitContent(const Document& doc, const Node& n, const DMat23& world,
                     ScopeId scope, int instDepth, NodeId owner = kNullNode);
    // Emit the style pieces (fills incl. pattern expansion, then strokes) of a
    // path node at `world`.
    void EmitPath(const Document& doc, const Node& n, const DMat23& world,
                  ScopeId scope, NodeId owner);
    // The node's effective geometry: its own PathData, or a Boolean-modifier
    // derived path (stored stably in derivedPaths_). Returns the path + its
    // content hash. `n` must be a path node.
    const PathData* ResolveGeometry(const Document& doc, const Node& n,
                                    std::uint64_t& hashOut);
    // Expand a pattern fill: motif instances on a lattice, cut by the host's
    // stencil clip mask (`geo` = the host's resolved geometry + its hash).
    void EmitPattern(const Document& doc, const Fill& fill, const Node& host,
                     const PathData* geo, std::uint64_t geoHash,
                     const DMat23& world, ScopeId scope, NodeId owner);
    // A group that composites as a unit opens a scope; returns its id (or the
    // parent scope when the group is a plain pass-through layer).
    ScopeId OpenScopeIfNeeded(const Document& doc, const Node& group,
                              ScopeId parent, int depth);
    void GrowBounds(DVec2 p);

    std::vector<Drawable>       drawables_;
    std::vector<CompositeScope> scopes_;
    std::vector<PathData>       pageRects_;   // stable storage for page substrates
    // Boolean-modifier results (stable addresses; drawables borrow them).
    std::deque<PathData>        derivedPaths_;
    std::unordered_map<NodeId, PathData*> derivedByNode_;
    // Per-owner rendered bounds (selection outlines, box select, fit-selection).
    std::unordered_map<NodeId, DRect> nodeBounds_;
    int           maxDepth_ = 0;
    std::uint64_t version_  = 0;
    bool          compiled_ = false;
    Rect          bounds_{};
    bool          boundsValid_ = false;
};

} // namespace Ink
